### DISCUSSION TITLE
iCloud support

### DISCUSSION THREAD

**Discussion by jedahan** [tenJirka/reGenda#5] [Show and tell]
If you are using iCloud, heres how to configure it:

```yaml
url: https://caldav.icloud.com/
user: <your-apple-id-here>
password: <app-specific-password>
```

### How to make an app-specific-password?

From https://support.apple.com/en-us/102654

1. Sign in to [appleid.apple.com](https://appleid.apple.com/account/home).
2. In the Sign-In and Security section, select App-Specific Passwords.
3. Select Generate an app-specific password or select the Add button (Blue plus sign icon.), then follow the steps on your screen.
